// Generated by CoffeeScript 1.10.0
(function() {
  var generate;

  generate = function() {
    var generate_string, heading_string, i, j, key_words_list, len, len1, ref, template_list, word;
    heading_string = data['heading'][Math.floor(Math.random() * data['heading'].length)];
    generate_string = data['response'][Math.floor(Math.random() * data['response'].length)];
    key_words_list = [];
    template_list = data['template'][Math.floor(Math.random() * data['template'].length)];
    ref = template_list.split(" ");
    for (i = 0, len = ref.length; i < len; i++) {
      word = ref[i];
      if (word.indexOf('@') >= 0) {
        key_words_list.push(word.split('@').join(''));
      }
    }
    for (j = 0, len1 = key_words_list.length; j < len1; j++) {
      word = key_words_list[j];
      template_list = template_list.replace('@' + word, data[word][Math.floor(Math.random() * data[word].length)]);
    }
    $('#output').html('<p>' + heading_string + '</p>' + '<p>' + template_list + '</p>');
    return $('#generate').text(generate_string);
  };

  generate();

  $('#generate').click(function() {
    return generate();
  });

}).call(this);
