// Generated by CoffeeScript 1.10.0
(function() {
  $('#navicon').on("click", function() {
    return $('#mySidenav').css('width', '250px');
  });

  $('#closebtn').on("click", function() {
    return $('#mySidenav').css('width', '0px');
  });

}).call(this);
